lst=[]
fruit1=input("Enter the fruit:")
lst.append(fruit1)
fruit2=input("Enter the fruit:")
lst.append(fruit2)
fruit3=input("Enter the fruit:")
lst.append(fruit3)
fruit4=input("Enter the fruit:")
lst.append(fruit4)
fruit5=input("Enter the fruit:")
lst.append(fruit5)
fruit6=input("Enter the fruit:")
lst.append(fruit6)
fruit7=input("Enter the fruit:")
lst.append(fruit7)
print(lst)
