z=set()
n=int(input("Enter the number1:"))
z.add(n)
n=int(input("Enter the number2:"))
z.add(n)
n=int(input("Enter the number3:"))
z.add(n)
n=int(input("Enter the number4:"))
z.add(n)
n=int(input("Enter the number5:"))
z.add(n)
n=int(input("Enter the number6:"))
z.add(n)
n=int(input("Enter the number7:"))
z.add(n)
n=int(input("Enter the number8:"))
z.add(n)
print(z)